name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # runs every midnight UTC
  workflow_dispatch:     # allow manual runs

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Pacman graph
        uses: mauriciovieira/pacman-contribution-graph-action@v0.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: sangampradhan
          output_path: dist

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
